# Generated by Django 5.2.8 on 2025-11-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dash',
            name='ad_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Reklama narxi so'mda", max_digits=10),
        ),
        migrations.AddField(
            model_name='dash',
            name='contact',
            field=models.CharField(default='', help_text='Telefon raqaming yoki Telegram URL (masalan: +99890..., yoki https://t.me/username)', max_length=255),
            preserve_default=False,
        ),
    ]
