# Generated by Django 5.2.8 on 2025-12-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal_app', '0004_rename_article_maqola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maqola',
            name='author',
            field=models.CharField(max_length=150),
        ),
    ]
