# Generated by Django 5.2.8 on 2025-12-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal_app', '0005_alter_maqola_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='maqola',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='article_files'),
        ),
    ]
