# Generated by Django 5.2.8 on 2025-12-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal_app', '0006_maqola_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaqolaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('dash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jurnal_app.maqola')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
