# Generated by Django 5.2.8 on 2025-12-04 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jurnal_app', '0007_maqolacomment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maqolacomment',
            old_name='dash',
            new_name='maqola',
        ),
    ]
